<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>错误处理</title>
</head>
<body>
    <script>
        //不能用try catch
        function f(val) {
            return new Promise((resolve, reject) => {
                if(val) {
                    resolve({ name: '小明'});  //只能传递一个参数
                }else {
                    reject('404');
                }
            })
        }

        // f(true)
        //     .then((data) => {
        //         console.log('成功', data)
        //     }, () => {
        //         console.log('失败')
        //     })
        f(true)
            .then(data =>{
                console.log(data)
                return f(false)
            })
            .then(() => {
                console.log('我永远不会输出')
            })
            .catch(e => {
               console.log(e)
                return f(false)
            })
    </script>
</body>
</html>